package com.realsil.android.wifiConfig.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.realsil.android.wifiConfig.greendao.WifiConfigDevice;

import com.realsil.android.wifiConfig.greendao.WifiConfigDeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wifiConfigDeviceDaoConfig;

    private final WifiConfigDeviceDao wifiConfigDeviceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wifiConfigDeviceDaoConfig = daoConfigMap.get(WifiConfigDeviceDao.class).clone();
        wifiConfigDeviceDaoConfig.initIdentityScope(type);

        wifiConfigDeviceDao = new WifiConfigDeviceDao(wifiConfigDeviceDaoConfig, this);

        registerDao(WifiConfigDevice.class, wifiConfigDeviceDao);
    }
    
    public void clear() {
        wifiConfigDeviceDaoConfig.getIdentityScope().clear();
    }

    public WifiConfigDeviceDao getWifiConfigDeviceDao() {
        return wifiConfigDeviceDao;
    }

}
