package com.realsil.android.wifiConfig.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WIFI_CONFIG_DEVICE".
 */
public class WifiConfigDevice {

    private Long id;
    private String deviceName;
    /** Not-null value. */
    private String deviceAddress;
    private Boolean isConnected;
    private Integer rssi;

    public WifiConfigDevice() {
    }

    public WifiConfigDevice(Long id) {
        this.id = id;
    }

    public WifiConfigDevice(Long id, String deviceName, String deviceAddress, Boolean isConnected, Integer rssi) {
        this.id = id;
        this.deviceName = deviceName;
        this.deviceAddress = deviceAddress;
        this.isConnected = isConnected;
        this.rssi = rssi;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /** Not-null value. */
    public String getDeviceAddress() {
        return deviceAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeviceAddress(String deviceAddress) {
        this.deviceAddress = deviceAddress;
    }

    public Boolean getIsConnected() {
        return isConnected;
    }

    public void setIsConnected(Boolean isConnected) {
        this.isConnected = isConnected;
    }

    public Integer getRssi() {
        return rssi;
    }

    public void setRssi(Integer rssi) {
        this.rssi = rssi;
    }

}
